version: "3"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - nats

  subscriber:
    build:
      context: ./subscriber
    networks:
      - nats
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222

  publisher:
    build:
      context: ./publisher
    networks:
      - nats
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222

networks:
  nats:
    external: true
